### ISSUE TITLE
Running for first time

### ISSUE THREAD

**Issue by M0hsend** [ePSIC-DLS/ParticleSpy#45]
When you install and run ParticleSpy for the first time you get the following error:
`OSError: Unable to create file (unable to open file: name = '.../ParticleSpy/ParticleSpy/parameters/parameters_previous.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)`

Need to catch this if there is no pre-existing parameters file, e.g. to create one with some initial parameters populated.

**Comment by M0hsend** [comment]
So the file exists and I am still getting this error. Is this due to running in Linux? @TomSlater

**Comment by TomSlater** [comment]
The file should be included when first installing so I'm not sure why you're getting this error. In all honesty, the file was there to enable an undo function in SegUI but I've never coded it in so it's actually redundant. We could just remove it for now.

**Comment by TomSlater** [comment]
This error may have cropped up using a conda installation as the parameters folder wasn't being installed correctly. This should now be fixed with the latest conda builds. I'm closing for now in any case.
