### ISSUE TITLE
Jupyter Notebook errors

### ISSUE THREAD

**Issue by CameronGBell** [ePSIC-DLS/ParticleSpy#57]
Example `Basic Example.ipynb` contains some lengthy errors.

Think this is contributing to the 80% Jupyter notebook language score from github.

**Comment by TomSlater** [comment]
We could move the example to a separate repository, as is done in Hyperspy and pyxem.

It might be a good idea to add a few different examples at that point.

**Comment by TomSlater** [comment]
I've split the example notebooks off into a separate repo and re-run to fix this.
