### ISSUE TITLE
Inconsistency in case of 'parameters' folder

### ISSUE THREAD

**Issue by jlaehne** [ePSIC-DLS/ParticleSpy#69]
On linux, when I install from pip, the folder `parameters` has a lower case name, which results in failure of the code. Here in the repo it is upper case, but references to it are mixed, e.g.:
https://github.com/ePSIC-DLS/ParticleSpy/blob/5225e331dd512639c9bb4a1b69bffeef3f881af4/ParticleSpy/ParticleAnalysis.py#L356
https://github.com/ePSIC-DLS/ParticleSpy/blob/5225e331dd512639c9bb4a1b69bffeef3f881af4/ParticleSpy/SegUI.py#L363

I think it would be preferable to have lower case `parameters` in the folder name and in any reference to this folder to avoid failures.

**Comment by TomSlater** [comment]
Thanks for pointing this out. I'm planning to switch everything to lower case only and will try to do this asap to solve this issue. Aiming for the next release.

**Comment by jlaehne** [comment]
Cool, I just fixed it locally for the meantime ;-)
